---
cards:
- entities:
  - entity: switch.laundry_fan
    name: Fan
    secondary_info: "{{states('sensor.laundry_fan_power')}} W"
    type: custom:secondaryinfo-entity-row
  - entity: sensor.laundry_humidity
  - entity: sensor.laundry_temperature
  type: entities
columns: 1
square: false
title: Climate
type: grid
