---
cards:
- entities:
  - entities:
    - entities:
      - entity: light.stairwell_downlight_1
        name: Downlight 1
        secondary_info: "{{states('sensor.stairwell_downlight_1_power')}} W"
        type: custom:secondaryinfo-entity-row
      - entity: light.stairwell_downlight_2
        name: Downlight 2
        secondary_info: "{{states('sensor.stairwell_downlight_2_power')}} W"
        type: custom:secondaryinfo-entity-row
      head:
        entity: light.stairwell_downlights_a
        name: Downlights A
        secondary_info: "{{states('sensor.stairwell_downlights_a_power')}} W"
        type: custom:secondaryinfo-entity-row
      type: custom:fold-entity-row
    - entity: light.stairwell_downlight_3
      name: Downlight 3
      secondary_info: "{{states('sensor.stairwell_downlight_3_power')}} W"
      type: custom:secondaryinfo-entity-row
    - entity: light.stairwell_downlight_4
      name: Downlight 4
      secondary_info: "{{states('sensor.stairwell_downlight_4_power')}} W"
      type: custom:secondaryinfo-entity-row
    head:
      entity: light.stairwell_downlights
      name: Downlights
      secondary_info: "{{states('sensor.stairwell_downlights_power')}} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  - entities:
    - entity: light.stairwell_nightlight_1
      name: Nightlight 1
      secondary_info: "{{states('sensor.stairwell_nightlight_1_power')}} W"
      type: custom:secondaryinfo-entity-row
    - entity: light.stairwell_nightlight_2
      name: Nightlight 2
      secondary_info: "{{states('sensor.stairwell_nightlight_2_power')}} W"
      type: custom:secondaryinfo-entity-row
    - entity: light.stairwell_nightlight_3
      name: Nightlight 3
      secondary_info: "{{states('sensor.stairwell_nightlight_3_power')}} W"
      type: custom:secondaryinfo-entity-row
    - entity: light.stairwell_nightlight_4
      name: Nightlight 4
      secondary_info: "{{states('sensor.stairwell_nightlight_4_power')}} W"
      type: custom:secondaryinfo-entity-row
    - entity: light.stairwell_nightlight_5
      name: Nightlight 5
      secondary_info: "{{states('sensor.stairwell_nightlight_5_power')}} W"
      type: custom:secondaryinfo-entity-row
    - entity: light.stairwell_nightlight_6
      name: Nightlight 6
      secondary_info: "{{states('sensor.stairwell_nightlight_6_power')}} W"
      type: custom:secondaryinfo-entity-row
    head:
      entity: light.stairwell_nightlights
      name: Nightlights
      secondary_info: "{{states('sensor.stairwell_nightlights_power')}} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid
